apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: eks-course
  - name: ng-mixed
    minSize: 3
    maxSize: 4
    instanceDistribution:
       maxPrice: 0.2
       instanceType: t2.nano
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
    ssh:
        publicKeyName: eks-course